version: '3.9'

services:
  postgres:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=indexer
      - POSTGRES_USER=indexer
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - indexer-network

  redis:
    image: 'redis:7.2-alpine'
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - indexer-network

  lazy-indexer:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://indexer:password@postgres:5432/indexer
      - REDIS_URL=redis://redis:6379
    networks:
      - indexer-network

volumes:
  postgres-data:
  redis-data:

networks:
  indexer-network:
