version: '3.9'

services:
  postgres:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=indexer
      - POSTGRES_USER=indexer
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s       # Check every 5 seconds (faster)
      timeout: 5s        # Allow up to 5 seconds for a response
      retries: 3         # Fail after 3 unsuccessful attempts
      start_period: 10s  # Reduce the initial wait before the first check
    networks:
      - indexer-network

  redis:
    image: 'redis:7.2-alpine'
    restart: unless-stopped
    command: --loglevel warning --maxmemory-policy noeviction
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 5s       # Reduced check interval for faster readiness detection
      timeout: 5s
      retries: 3
      start_period: 5s   # Start checking after 5 seconds
    networks:
      - indexer-network

volumes:
  postgres-data:
  redis-data:

networks:
  indexer-network:
