name: Build, Backfill, and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # We want to run the backfill first, so we won't push yet
          tags: yourusername/lazy-indexer:latest

      # Step 5: Run the backfill in the container
      - name: Run backfill in Docker container
        run: |
          docker run --rm yourusername/lazy-indexer:latest yarn migrate && yarn backfill

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gabrieltemtsen/lazy-indexer-1:latest

      # Step 7: Verify the image is on Docker Hub
      - name: Image exists on Docker Hub
        run: docker pull yourusername/lazy-indexer:latest
